# Generated by Django 2.1 on 2018-08-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='rhyme_toggle',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='verse',
            name='rhyme_mode',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='verse',
            name='rhyme_style_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verse',
            name='sentence_count',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='verse',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
